module onlinesolution

include("onlineSolutionUtils.jl")
using .onlineSolutionUtils
export updateTimeWindowsOnline! 
export onlineAlgorithm

include("OnlineSolutionResults.jl")
using .OnlineSolutionResults
export createGantChartOfSolutionOnline, createGantChartOfSolutionOnlineComparison,writeOnlineKPIsToFile,processResults,createGantChartOfSolutionAndEventOnline, createGantChartOfSolutionAndEventOnlineComparison, plotRoutesOnline
export plotRelocation,createGantChartOfSolutionAnticipation

end
