module waitingstrategies

global N_TIME_PERIODS = 24

include("GeneratePredictedDemand.jl")
using .GeneratePredictedDemand
export generatePredictedDemand,generatePredictedVehiclesDemand,generatePredictedVehiclesDemandInPeriod,generatePredictedVehiclesDemandInHorizon,getProbabilityGrid

include("RelocateVehicleUtils.jl")
using .RelocateVehicleUtils
export determineWaitingLocation,determineActiveVehiclesPrCell,determineVehicleBalancePrCell,determineWaitingLocation2,determineActiveVehiclesPrCell

include("WaitingStrategiesPlots.jl")
using .WaitingStrategiesPlots
export plotRequestsAndVehiclesWait

end # module waitingstrategies
