name = "utils"
uuid = "d9eeeeb4-94be-4641-9ce8-3b648504a7dd"
authors = ["JasmineRolin <75620908+JasmineRolin@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
OpenStreetMapX = "86cd37e6-c0ff-550b-95fe-21d72c8d4fc9"

[compat]
Dates = "1.11.0"
OpenStreetMapX = "0.4.1"
