name = "utils"
uuid = "d9eeeeb4-94be-4641-9ce8-3b648504a7dd"
authors = ["JasmineRolin <75620908+JasmineRolin@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Dates = "1.11.0"
